# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US

reviews:
  auto_review:
    enabled: true
    drafts: false
  high_level_summary: true
  auto_title_placeholder: "@ai"

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto
